sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: e10adc3949ba59abbe56e057f20f883e
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10

#spring:
#  profiles:
#    active: dev
#  redis:
#    host: ${sky.redis.host}
#    port: ${sky.redis.port}
#    password: ${sky.redis.password}
#    database: ${sky.redis.database}